### ISSUE TITLE
Add "How to integrate with Django" to the Readme

### ISSUE THREAD

**Issue by jensenbox** [getludic/ludic#13]
A brief doc on how to integrate with an existing Django app would be extremely useful.

**Comment by paveldedik** [comment]
Hi,
thank you for creating the issue. I haven't thought about Django integration yet, but I am open to suggestions/contributions on what would be the best way to use the framework together with Django.

**Comment by kennethdamica** [comment]
Personally I don't think I need any official support, but a quick note on the best way to do the integration myself would be helpful. 

For example, if I create a view like this 
```
def index(request):
    return HttpResponse(Box(MessageSuccess(Title("Message"), "This is a message")))
```
This returns 
```
<MessageSuccess>
<Title>Message</Title>
This is a message
</MessageSuccess>
```

However since `MessageSuccess` is not defined, this just renders the plain text. 

What's the best way to include all the Ludic class definitions in my header?

**Comment by paveldedik** [comment]
There are two things you need to do:

1. call `.to_html()` on the component before you pass it to `HttpResponse`
2. you also need to render loaded CSS (if you are using components which declare it) e.g. in the `<head>` section of the HTML page, another option is to dump it to a static file. You load CSS from components with:

```python
from ludic.html import style

style.load()
```

Usually, you want to include that in the `<head>` section as I already mentioned. It is described here: https://getludic.dev/docs/styles#integration-in-a-page-component

---

That said, I would like to make it work without the explicit `.to_html()` call, to update your example, it should at least work like this:

```python
def index(request: HttpRequest) -> LudicResponse:
    return LudicResponse(Box(MessageSuccess(Title("Message"), "This is a message")))
```

or ideally:

```python
def index(request: HttpRequest) -> Box:
    return Box(MessageSuccess(Title("Message"), "This is a message"))
```

Currently, you can probably make it only work like this:

```python
def index(request):
    return HttpResponse(Box(MessageSuccess(Title("Message"), "This is a message")).to_html())

**Comment by kennethdamica** [comment]
Thanks for the detailed response. I've got it working now. 

For posterity here's what I have for my minimal example:

```python
from django.http import HttpResponse

from ludic.catalog.layouts import Box
from ludic.html import html, head, body, style
from ludic.catalog.messages import (
    MessageSuccess,
    Title
)

def index(request):
    return HttpResponse(
        html(
            head(
                style.load(cache=True)
            ),
            body(
                Box(MessageSuccess(Title("Message"), "This is a message"))
            ),
        ).to_html()
    )
```

**Comment by Mte90** [comment]
I think that we just need an example where it is used a Django url for the HTMX stuff and it's done.
Maybe ludic on Django should not load Starlette and the other libraries, maybe not download it all too?

**Comment by paveldedik** [comment]
@Mte90 I'll get to this soon, I think I'll create new extra `ludic[django]` so that starlette and other unnecessary stuff are not installed. But I still want the catalog to be available if someone wants to use it. A Middleware for django will probably also need to be added since the way f-strings work in ludic could create potential memory leaks without cleaning the cache that is created.

**Comment by Mte90** [comment]
The latest release I think that close this ticket :-)

**Comment by paveldedik** [comment]
Yep, you are faster than me :-)

Here is a guide: https://getludic.dev/docs/integrations
